// GitFolio — Shared TypeScript Interfaces
// These types are shared between frontend and backend.

export interface PinnedRepo {
  name: string;
  description: string | null;
  url: string;
  homepageUrl: string | null;
  stargazerCount: number;
  forkCount: number;
  primaryLanguage: string | null;
  topics: string[];
}

export interface Repo {
  name: string;
  description: string | null;
  url: string;
  homepageUrl: string | null;
  stargazerCount: number;
  forkCount: number;
  primaryLanguage: string | null;
  topics: string[];
  pushedAt: string;
  isArchived: boolean;
  isFork: boolean;
}

export interface GitHubData {
  profile: {
    name: string;
    bio: string;
    avatar: string;
    location: string | null;
    company: string | null;
    blog: string | null;
    followers: number;
    publicRepos: number;
  };
  pinnedRepos: PinnedRepo[];
  allRepos: Repo[];
  topLanguages: string[]; // recency-weighted, max 6
  contributions: {
    totalLastYear: number;
  };
}

export interface UserPreferences {
  role: 'frontend' | 'backend' | 'fullstack' | 'ml' | 'devops' | 'student';
  vibe: 'minimal' | 'dark' | 'warm' | 'corporate' | 'hacker';
  accentColor: string;
  layout: 'grid' | 'list' | 'casestudy' | 'timeline';
  highlights: string[];
  lookingForJob: boolean;
  customTagline: string | null;
  templateId: 'default' | 'neo-brutalism' | 'glassmorphism' | 'retro-rpg';
}

export interface GeneratedCopy {
  headline: string;
  about: string;
  projectDescriptions: Record<string, string>;
  isFallback: false;
}

export interface FallbackCopy {
  headline: string;
  about: string;
  projectDescriptions: Record<string, string>;
  isFallback: true;
  fallbackReason: string;
}

export interface Portfolio {
  id: string;
  userId: string;
  githubData: GitHubData;
  preferences: UserPreferences;
  generatedCopy: GeneratedCopy | FallbackCopy | null;
  templateId: string;
  isPublished: boolean;
  viewCount: number;
  updatedAt: string;
}

// API error type for typed error handling
export interface ApiError {
  message: string;
  code: string;
  status: number;
}

// ============================================
// Enriched GitHub Data Interfaces
// Returned by POST /api/github/fetch-enriched and GET /api/github/enriched/:username
// ============================================

/**
 * Byte counts per language across all repos, converted to percentages.
 * Aggregated from the top 8 repos by star count.
 * All values sum to 100.
 *
 * FRONTEND NOTE: Values are percentages (0–100). Use them directly for rendering
 * bar charts or pie charts. Keys are language names (e.g. "TypeScript", "Python").
 */
export interface LanguageBreakdown {
  [language: string]: number; // percentage, all values sum to 100
}

/**
 * A single repo ranked by how many commits the authenticated user made in the last 12 months.
 * Returned as part of EnrichedGitHubData.mostActiveRepos.
 *
 * BACKWARD COMPATIBLE UPGRADE: qualityScore and qualityLabel are new fields added
 * in the commit quality analysis pass. Existing consumers reading only name/commitCount/url
 * are unaffected — those fields remain unchanged.
 *
 * FRONTEND NOTE:
 * - Repos are pre-sorted by commitCount descending. Array length is at most 6.
 * - qualityScore is 0–100. Use alongside commitCount for a richer picture.
 * - qualityLabel is one of: "Excellent" | "Good" | "Average" | "Needs improvement" | "Poor".
 * - qualityScore/qualityLabel may be absent for repos not included in the quality analysis
 *   (those beyond the top 3 by commit count). Always guard with a null check.
 */
export interface ActiveRepo {
  name: string;
  commitCount: number; // commits by this user in the last 12 months
  url: string;
  qualityScore?: number; // 0–100 composite commit quality score (present on top 3 repos only)
  qualityLabel?: string; // human-readable quality label (present on top 3 repos only)
}

/**
 * Commit frequency patterns extracted from commit timestamps across the top 3 repos.
 * Used to understand when the developer is most active.
 *
 * FRONTEND NOTE:
 * - byDayOfWeek: keys are exact strings "Sun"–"Sat". Values are commit counts.
 * - byHourOfDay: keys are strings "0"–"23" (UTC hour). Values are commit counts.
 * - peakDay / peakHour are pre-computed for convenience.
 * - summary is a human-readable string e.g. "Primarily commits Wednesday afternoons (UTC)".
 */
export interface CommitPatterns {
  byDayOfWeek: {
    Sun: number;
    Mon: number;
    Tue: number;
    Wed: number;
    Thu: number;
    Fri: number;
    Sat: number;
  };
  byHourOfDay: Record<string, number>; // key is hour "0"–"23", value is commit count
  peakDay: string; // e.g. "Wednesday"
  peakHour: number; // e.g. 17 (5 PM UTC)
  summary: string; // e.g. "Primarily commits Wednesday afternoons (UTC)"
}

/**
 * A single skill cluster inferred by the AI from repo evidence.
 * Part of EnrichedGitHubData.skillClusters. Generated by POST /api/github/fetch-enriched.
 *
 * FRONTEND NOTE: indicators is an array of bullet-point strings ready to render as a list.
 * evidenceRepos are raw repo names (no URL). Cross-reference with GitHubData.allRepos for URLs.
 */
export interface SkillCluster {
  skillName: string; // e.g. "Full-Stack TypeScript Development"
  technologies: string[]; // e.g. ["TypeScript", "Node.js", "React"]
  indicators: string[]; // 2–3 bullet points of what the code evidence shows
  evidenceRepos: string[]; // repo names that support this cluster
}

/**
 * A single category of forked repo activity inferred by the AI.
 * Part of EnrichedGitHubData.forkInterests. Generated by POST /api/github/fetch-enriched.
 *
 * FRONTEND NOTE: repos are raw repo names (owner/name format from GitHub).
 * description is a single sentence ready to render directly.
 */
export interface ForkInterest {
  category: string; // e.g. "AI/ML Exploration"
  repos: string[]; // forked repo names in this category (owner/repo format)
  description: string; // one sentence about what this pattern reveals
}

/**
 * Working style scores calculated from repo behaviour metrics (no AI).
 * The AI only writes the summary sentence — scores are pure arithmetic.
 * Part of EnrichedGitHubData.workingStyle.
 *
 * FRONTEND NOTE:
 * - explorationScore: 0 = pure execution focus, 100 = pure exploration/breadth
 * - breadthScore: 0 = narrow single-domain focus, 100 = very broad scope across domains
 * - summary is an AI-written one-sentence description of the developer's style
 */
export interface WorkingStyle {
  explorationScore: number; // 0–100: 0 = pure execution, 100 = pure exploration
  breadthScore: number; // 0–100: 0 = narrow focus, 100 = broad scope
  summary: string; // AI-written one-sentence human-readable description
}

/**
 * The full enriched GitHub data payload.
 * Stored in portfolios.enriched_github_data (jsonb column).
 * Returned by:
 *   - POST /api/github/fetch-enriched (after generation)
 *   - GET  /api/github/enriched/:username (after it has been generated)
 *
 * FRONTEND NOTE:
 * - skillClusters may be [] if AI generation failed. Always check length before rendering.
 * - forkInterests may be [] if the user has no forks or AI generation failed.
 * - externalReposContributed may be [] if the user has no external contributions.
 * - commitQuality may be null if the quality analysis failed entirely — check before rendering.
 * - generatedAt is an ISO 8601 timestamp string. Parse with new Date(generatedAt).
 * - All arrays are pre-sorted by relevance/frequency (most important first).
 */
export interface EnrichedGitHubData {
  languageBreakdown: LanguageBreakdown;
  mostActiveRepos: ActiveRepo[]; // top 6, sorted by commitCount descending
  externalPRsMerged: number; // count of merged PRs in repos the user does not own
  externalReposContributed: string[]; // names of those external repos
  commitPatterns: CommitPatterns;
  skillClusters: SkillCluster[]; // 4–6 AI-generated clusters, may be [] on failure
  forkInterests: ForkInterest[]; // 2–4 AI-generated categories, may be [] on failure
  workingStyle: WorkingStyle;
  commitQuality: CommitQualityAnalysis | null; // NEW — null if quality analysis failed entirely
  generatedAt: string; // ISO 8601 timestamp of when this enrichment was generated
}

// ============================================
// Commit Quality Analysis Interfaces
// Added to EnrichedGitHubData.commitQuality
// ============================================

/**
 * Breakdown of a single commit quality dimension.
 * Each dimension is scored independently before being combined
 * into the composite score.
 *
 * FRONTEND NOTE: All scores are 0–100 integers. rawValue is the
 * underlying metric before conversion to a score (e.g. the actual
 * fix ratio percentage, not the score derived from it). Use rawValue
 * for displaying the actual measurement; use score for the visual
 * quality indicator.
 */
export interface QualityDimension {
  score: number; // 0–100 quality score for this dimension
  rawValue: number; // the underlying metric (percentage, ratio, etc.) before scoring
  label: string; // human-readable one-line description of the measurement
  // e.g. "68% of messages are descriptive and specific"
}

/**
 * Full commit quality analysis for a single repository.
 * Generated by sampling up to 25 commits from the repo (full detail) and
 * up to 50 commit messages (for AI and category analysis).
 *
 * FRONTEND NOTE:
 * - sampleSize tells you how many commits were actually analyzed (max 25).
 * - For repos with fewer than 25 commits, sampleSize < 25.
 * - For repos with fewer than 3 commits, this repo is omitted from qualityByRepo entirely.
 * - aiObservation may be null if the AI call failed — always guard before rendering.
 * - messageCategories values are percentages that sum to 100.
 */
export interface RepoCommitQuality {
  repoName: string; // name of the repository analyzed
  sampleSize: number; // number of commits actually analyzed (max 25)

  // Individual dimension scores — see QualityDimension for field descriptions
  messageQuality: QualityDimension; // AI-scored 0–100 (weight: 30%)
  atomicity: QualityDimension; // file/line size appropriateness 0–100 (weight: 20%)
  fixRatio: QualityDimension; // fix vs feature commit ratio 0–100 (weight: 20%)
  testCoverage: QualityDimension; // % of commits touching test files 0–100 (weight: 15%)
  conventionalCommits: QualityDimension; // % following conventional commits spec 0–100 (weight: 5%)

  // Composite score — weighted average of all dimension scores
  compositeScore: number; // 0–100, rounded to nearest integer
  compositeLabel: string; // "Excellent" | "Good" | "Average" | "Needs improvement" | "Poor"

  /**
   * Percentage breakdown of commit message categories.
   * All values are percentages that sum to 100.
   * Derived from keyword matching — see categoriseMessages() in commitQuality.ts.
   *
   * FRONTEND NOTE: Use for a donut chart or breakdown list.
   */
  messageCategories: {
    feat: number; // feature / addition commits
    fix: number; // bug fix commits
    docs: number; // documentation commits
    refactor: number; // refactoring commits
    test: number; // test commits
    chore: number; // chore / maintenance commits
    other: number; // uncategorised commits
  };

  /**
   * AI-generated one-sentence observation about this developer's commit style in this repo.
   * e.g. "Commits are consistently descriptive with good use of conventional format,
   * though test coverage in commits is low."
   *
   * FRONTEND NOTE: May be null if the AI call failed. Render scores without it — do not
   * show an empty card or placeholder text.
   */
  aiObservation: string | null;
}

/**
 * Top-level commit quality analysis across all analyzed repos.
 * Added as EnrichedGitHubData.commitQuality.
 * May be null on EnrichedGitHubData if the analysis failed entirely.
 *
 * FRONTEND NOTE:
 * - qualityByRepo only includes repos where 3+ commits were found and analyzed.
 *   It will never include repos with < 3 user commits. Array length is 1–3.
 * - qualityByRepo is sorted by compositeScore descending (best repo first).
 * - overall.compositeScore is the headline number for the "Commit Quality" section.
 * - overallSummary may be null — render dimension scores without it if so.
 * - consistencyScoreNote will be present and non-empty if consistency could not
 *   be calculated (e.g. no contribution calendar data). Otherwise null.
 */
export interface CommitQualityAnalysis {
  // Per-repo breakdown — max 3 repos, sorted by compositeScore descending
  qualityByRepo: RepoCommitQuality[];

  // Aggregate scores across all analyzed repos (weighted by commit count)
  overall: {
    compositeScore: number; // 0–100 weighted average across all repos
    compositeLabel: string; // "Excellent" | "Good" | "Average" | "Needs improvement" | "Poor"
    messageQualityScore: number; // 0–100
    atomicityScore: number; // 0–100
    fixRatioScore: number; // 0–100
    testCoverageScore: number; // 0–100
    consistencyScore: number; // 0–100, computed from contribution calendar (not per-repo)
    conventionalCommitsScore: number; // 0–100
  };

  /**
   * AI-written 2–3 sentence summary of the developer's overall commit quality.
   * References specific dimension scores where relevant.
   *
   * FRONTEND NOTE: May be null if the AI call failed. Fall back to showing individual
   * dimension scores without a summary — do not show an empty block.
   */
  overallSummary: string | null;

  // Note if consistency could not be calculated (e.g. missing contribution calendar)
  // null means consistency was computed successfully
  consistencyScoreNote: string | null;

  // Metadata about the analysis
  reposAnalyzed: string[]; // names of repos that were sampled
  totalCommitsSampled: number; // total full-detail commits examined across all repos
  generatedAt: string; // ISO 8601 timestamp of when this analysis was generated
}

