// GitFolio — Shared TypeScript Interfaces
// These types are shared between frontend and backend.

export interface PinnedRepo {
  name: string;
  description: string | null;
  url: string;
  homepageUrl: string | null;
  stargazerCount: number;
  forkCount: number;
  primaryLanguage: string | null;
  topics: string[];
}

export interface Repo {
  name: string;
  description: string | null;
  url: string;
  homepageUrl: string | null;
  stargazerCount: number;
  forkCount: number;
  primaryLanguage: string | null;
  topics: string[];
  pushedAt: string;
  isArchived: boolean;
  isFork: boolean;
}

export interface GitHubData {
  profile: {
    name: string;
    bio: string;
    avatar: string;
    location: string | null;
    company: string | null;
    blog: string | null;
    followers: number;
    publicRepos: number;
  };
  pinnedRepos: PinnedRepo[];
  allRepos: Repo[];
  topLanguages: string[]; // recency-weighted, max 6
  contributions: {
    totalLastYear: number;
  };
}

export interface UserPreferences {
  role: 'frontend' | 'backend' | 'fullstack' | 'ml' | 'devops' | 'student';
  vibe: 'minimal' | 'dark' | 'warm' | 'corporate' | 'hacker';
  accentColor: string;
  layout: 'grid' | 'list' | 'casestudy' | 'timeline';
  highlights: string[];
  lookingForJob: boolean;
  customTagline: string | null;
}

export interface GeneratedCopy {
  headline: string;
  about: string;
  projectDescriptions: Record<string, string>;
  isFallback: false;
}

export interface FallbackCopy {
  headline: string;
  about: string;
  projectDescriptions: Record<string, string>;
  isFallback: true;
  fallbackReason: string;
}

export interface Portfolio {
  id: string;
  userId: string;
  githubData: GitHubData;
  preferences: UserPreferences;
  generatedCopy: GeneratedCopy | FallbackCopy | null;
  templateId: string;
  isPublished: boolean;
  viewCount: number;
  updatedAt: string;
}

// API error type for typed error handling
export interface ApiError {
  message: string;
  code: string;
  status: number;
}

// ============================================
// Enriched GitHub Data Interfaces
// Returned by POST /api/github/fetch-enriched and GET /api/github/enriched/:username
// ============================================

/**
 * Byte counts per language across all repos, converted to percentages.
 * Aggregated from the top 8 repos by star count.
 * All values sum to 100.
 *
 * FRONTEND NOTE: Values are percentages (0–100). Use them directly for rendering
 * bar charts or pie charts. Keys are language names (e.g. "TypeScript", "Python").
 */
export interface LanguageBreakdown {
  [language: string]: number; // percentage, all values sum to 100
}

/**
 * A single repo ranked by how many commits the authenticated user made in the last 12 months.
 * Returned as part of EnrichedGitHubData.mostActiveRepos.
 *
 * FRONTEND NOTE: Repos are pre-sorted by commitCount descending. Array length is at most 6.
 */
export interface ActiveRepo {
  name: string;
  commitCount: number; // commits by this user in the last 12 months
  url: string;
}

/**
 * Commit frequency patterns extracted from commit timestamps across the top 3 repos.
 * Used to understand when the developer is most active.
 *
 * FRONTEND NOTE:
 * - byDayOfWeek: keys are exact strings "Sun"–"Sat". Values are commit counts.
 * - byHourOfDay: keys are strings "0"–"23" (UTC hour). Values are commit counts.
 * - peakDay / peakHour are pre-computed for convenience.
 * - summary is a human-readable string e.g. "Primarily commits Wednesday afternoons (UTC)".
 */
export interface CommitPatterns {
  byDayOfWeek: {
    Sun: number;
    Mon: number;
    Tue: number;
    Wed: number;
    Thu: number;
    Fri: number;
    Sat: number;
  };
  byHourOfDay: Record<string, number>; // key is hour "0"–"23", value is commit count
  peakDay: string; // e.g. "Wednesday"
  peakHour: number; // e.g. 17 (5 PM UTC)
  summary: string; // e.g. "Primarily commits Wednesday afternoons (UTC)"
}

/**
 * A single skill cluster inferred by the AI from repo evidence.
 * Part of EnrichedGitHubData.skillClusters. Generated by POST /api/github/fetch-enriched.
 *
 * FRONTEND NOTE: indicators is an array of bullet-point strings ready to render as a list.
 * evidenceRepos are raw repo names (no URL). Cross-reference with GitHubData.allRepos for URLs.
 */
export interface SkillCluster {
  skillName: string; // e.g. "Full-Stack TypeScript Development"
  technologies: string[]; // e.g. ["TypeScript", "Node.js", "React"]
  indicators: string[]; // 2–3 bullet points of what the code evidence shows
  evidenceRepos: string[]; // repo names that support this cluster
}

/**
 * A single category of forked repo activity inferred by the AI.
 * Part of EnrichedGitHubData.forkInterests. Generated by POST /api/github/fetch-enriched.
 *
 * FRONTEND NOTE: repos are raw repo names (owner/name format from GitHub).
 * description is a single sentence ready to render directly.
 */
export interface ForkInterest {
  category: string; // e.g. "AI/ML Exploration"
  repos: string[]; // forked repo names in this category (owner/repo format)
  description: string; // one sentence about what this pattern reveals
}

/**
 * Working style scores calculated from repo behaviour metrics (no AI).
 * The AI only writes the summary sentence — scores are pure arithmetic.
 * Part of EnrichedGitHubData.workingStyle.
 *
 * FRONTEND NOTE:
 * - explorationScore: 0 = pure execution focus, 100 = pure exploration/breadth
 * - breadthScore: 0 = narrow single-domain focus, 100 = very broad scope across domains
 * - summary is an AI-written one-sentence description of the developer's style
 */
export interface WorkingStyle {
  explorationScore: number; // 0–100: 0 = pure execution, 100 = pure exploration
  breadthScore: number; // 0–100: 0 = narrow focus, 100 = broad scope
  summary: string; // AI-written one-sentence human-readable description
}

/**
 * The full enriched GitHub data payload.
 * Stored in portfolios.enriched_github_data (jsonb column).
 * Returned by:
 *   - POST /api/github/fetch-enriched (after generation)
 *   - GET  /api/github/enriched/:username (after it has been generated)
 *
 * FRONTEND NOTE:
 * - skillClusters may be [] if AI generation failed. Always check length before rendering.
 * - forkInterests may be [] if the user has no forks or AI generation failed.
 * - externalReposContributed may be [] if the user has no external contributions.
 * - generatedAt is an ISO 8601 timestamp string. Parse with new Date(generatedAt).
 * - All arrays are pre-sorted by relevance/frequency (most important first).
 */
export interface EnrichedGitHubData {
  languageBreakdown: LanguageBreakdown;
  mostActiveRepos: ActiveRepo[]; // top 6, sorted by commitCount descending
  externalPRsMerged: number; // count of merged PRs in repos the user does not own
  externalReposContributed: string[]; // names of those external repos
  commitPatterns: CommitPatterns;
  skillClusters: SkillCluster[]; // 4–6 AI-generated clusters, may be [] on failure
  forkInterests: ForkInterest[]; // 2–4 AI-generated categories, may be [] on failure
  workingStyle: WorkingStyle;
  generatedAt: string; // ISO 8601 timestamp of when this enrichment was generated
}

